title: "Zeeshan Ahmad"
description: "Software engineer at tajawal — PHP and Javascript fanatic, open source lover and tinkerer"
url: "http://ziishaned.info"
author: "Zeeshan Ahmad"
keywords: "zeeshan,zeeshanahmadse,zeeshan ahmad,code,javascript,php,databases,entrepreneurship,startups,react,angular,javascript,docker,nodejs,laravel,lumen"

current_employer:
  name: Tajawal
  website: http://tajawal.com

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: ["résumé.pdf"]

permalink: pretty
timezone: Asia/Abu_Dhabi

plugins: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

about:
  github:
    username: ziishaned
    url: https://github.com/ziishaned
  medium:
    username: ziishaned
    url: https://medium.com/@ziishaned
  twitter:
    username: ziishaned
    url: https://twitter.com/ziishaned
  email:
    username: ziishaned@gmail.com
    url: mailto:ziishaned@gmail.com
