title: Zeeshan Ahmad
author: "Zeeshan Ahmad"
url: "http://ziishaned.info"

keywords: "zeeshan,ziishaned,zeeshan ahmad,code,javascript,php,databases,entrepreneurship,startups,react,angular"

github: ziishaned
medium: ziishaned
twitter: ziishaned
email: ziishaned@gmail.com

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: ["résumé.pdf"]

permalink: pretty
timezone: Asia/Abu_Dhabi

plugins: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

about:
  - name: Github
    username: ziishaned
    url: https://github.com/ziishaned
    class: github
  - name: Medium
    username: ziishaned
    url: https://medium.com/@ziishaned
    class: medium
  - name: Twitter
    username: ziishaned
    url: https://twitter.com/ziishaned
    class: twitter
  - name: Email
    username: ziishaned@gmail.com
    class: email
    url: mailto:ziishaned@gmail.com
